wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/train_image.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
checkpoint_dir:
  desc: null
  value: /scratch/cluster/nimit/checkpoints/resnet34_0.001_5e-05_64_v4.2
data_args:
  desc: null
  value:
    apply_transform: false
    batch_size: 64
    dataset_dir: /scratch/cluster/nimit/data/habitat/ppo_depth
device:
  desc: null
  value: cuda
max_epoch:
  desc: null
  value: 50
model_args:
  desc: null
  value:
    input_channel: 3
    pretrained: false
    resnet_model: resnet34
network:
  desc: null
  value: ddppo-direct
optimizer_args:
  desc: null
  value:
    lr: 0.001
    weight_decay: 5.0e-05
run_name:
  desc: null
  value: resnet34_0.001_5e-05_64_v4.2
